//! The grove head binary: launch the grove-owned **zellij substrate** and
//! present as a single binary (ADR-0015, ADR-0016; leaf
//! `060-harness-pane/040-grove-integration/030-zellij-launch`).
//!
//! `grove tui` becomes the *head binary*: it
//!
//! 1. writes grove's tamed config + a bars-free layout to a cache dir,
//! 2. binds the controller's unix-domain socket **before** anything connects,
//! 3. spawns zellij as a **child** (the controller persists alongside it — it
//!    does not `exec` zellij and vanish, ADR-0016), with a layout whose single
//!    pane runs `grove __dash-proxy --socket <path>`,
//! 4. accepts that proxy and serves the dashboard over the seam ([`tui::serve`]),
//! 5. tears down cleanly on exit (end the session, reap the child, remove the
//!    socket).
//!
//! The terminal-ownership split is the crux: the spawned zellij child inherits
//! the real tty and drives it full-screen; the controller (this same process)
//! never touches that tty — it only does socket I/O, rendering the dashboard
//! into the proxy pane *inside* zellij. So "controller persists alongside
//! zellij" and "zellij owns the screen" coexist with no contention.
//!
//! Per ADR-0013 this is controller/transport wiring, not the `RepoView` data
//! layer — it lives here, beside `tui`, not in `repo_view`.

use std::ffi::OsStr;
use std::io;
use std::os::unix::net::{UnixListener, UnixStream};
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::time::{Duration, Instant};

use anyhow::{Context, Result};

use crate::cli::RepoArgs;
use crate::repo;

/// Grove's tamed zellij **nav plugin** (ADR-0018), built by [`build.rs`] for
/// `wasm32-wasip1` and embedded here so grove stays a single binary. Written to
/// the cache dir at launch and referenced from the rendered config's `plugins`
/// alias — mirroring how [`CONFIG_TEMPLATE`]/[`LAYOUT_TEMPLATE`] are embedded and
/// written. The path lands in the config via the `{{NAV_WASM}}` placeholder (see
/// [`render_config`]).
const NAV_WASM: &[u8] = include_bytes!(env!("GROVE_NAV_WASM"));

/// Grove's tamed zellij config *template*, embedded in the binary and rendered
/// to the cache dir each launch (the `{{NAV_WASM}}` placeholder → the bundled
/// [`NAV_WASM`] plugin's cache path; see [`render_config`]). Provenance: the
/// throwaway 020 spike (`/tmp/grove-zellij-spike/config.kdl`), validated on
/// zellij 0.44.3; the leader → nav-plugin binding is ADR-0018.
///
/// Tamed so the composite reads as grove, not "a zellij session": locked mode
/// passes every key to the focused app; chrome/branding hidden. The control seam
/// is **`Ctrl-o`** (node-brief decision: zellij's default `Ctrl-g` collides with
/// nvim "show file info"; low-collision steer from the user), bound to
/// `LaunchOrFocusPlugin "file:…"` — it focuses the running [[nav plugin]] (the
/// permanent home sidebar; see [`LAYOUT_TEMPLATE`]), grove's leader-focused
/// command surface, *not* an unlock-to-`Normal` hop. That hop was the locked-mode
/// dead-end ADR-0018 fixed: with pane-nav binds stripped, unlocked `Normal` had
/// no bound way back to the dashboard. The plugin is named by its `file:` URL
/// (not a config alias) so the keybind focuses the *same* instance the layout
/// launched — alias resolution across a separately-passed layout is uncertain.
///
/// **Locked-only keymap.** With `clear-defaults=true` the map is grove's alone,
/// and now defines *only* the `locked` block (the leader + native `GoToTab`
/// switching). There are deliberately no unlocked modes: the earlier
/// `Ctrl-o`→`Normal`→`Ctrl-s`→`Scroll` path (and an `Alt-s` scroll seam) were
/// removed because, with zellij's status bar stripped, any non-locked mode is a
/// hint-less black hole the user can't escape. The scrollback/copy/search "free
/// wins" will return through the nav (which *shows* its keys); quitting is the
/// dashboard's `q` (controller teardown), not a zellij keybind.
///
/// `clear-defaults=true` (rather than `unbind`-ing the defaults) is itself
/// deliberate: zellij's `unbind` is unreliable for control keys (the default
/// `Ctrl-o`/`Ctrl-q` survive an `unbind`; zellij issues #2707, #3627), and an
/// additive merge left `Ctrl-o` *not* bound in locked mode at runtime even though
/// the config parsed clean. It is also what zellij's own "unlock-first" preset
/// and maintainer guidance recommend.
const CONFIG_TEMPLATE: &str = r##"// grove-owned zellij substrate config — generated by `grove tui` (ADR-0015/0018,
// leaf 030/070). Overwritten on every launch so a grove upgrade refreshes it; not
// meant for hand-editing.
//
// default_mode "locked" => zellij passes essentially every key straight through
//                          to the focused app (claude/codex chords, vim Esc &c).
//                          The control seam is Ctrl-o below — it focuses the
//                          grove-nav plugin (ADR-0018), not an unlock hop.
// pane_frames false      => no per-pane borders (chrome).
// simplified_ui true     => drop fancy UI glyphs.
// The bars-free layout (no tab/status-bar panes) + suppressed startup floats
// make the composite read as grove's own UI.

pane_frames false
default_mode "locked"
simplified_ui true
mouse_mode true
copy_on_select true
session_serialization true
show_release_notes false
show_startup_tips false

// clear-defaults=true: define grove's whole keymap from scratch (no reliance on
// the unreliable `unbind`). Only the locked block is defined — there are
// deliberately no unlocked modes (a hint-less mode is a trap with the status bar
// stripped). Grove drives panes externally via `zellij action`.
keybinds clear-defaults=true {
    // Locked is the default mode: every key passes through to the focused app
    // (dashboard / harness). The only interception is the leader, Ctrl-o, and the
    // native GoToTab switches (both bindable in locked mode).
    locked {
        // The leader (ADR-0018): focus the grove-nav plugin — grove's command
        // surface — which then receives every key while focused. A zellij keybind
        // cannot focus a tiled pane by id; only LaunchOrFocusPlugin can land focus
        // on a named surface, which is the whole reason the nav is a plugin. The
        // plugin runs as the permanent home sidebar (LAYOUT_TEMPLATE); naming it
        // by the same file: URL the layout uses guarantees this focuses that one
        // instance (no move_to_focused_tab — the nav lives on home, so Ctrl-o
        // brings you to it there).
        bind "Ctrl o" { LaunchOrFocusPlugin "file:{{NAV_WASM}}"; }
        // Workspace switching — native GoToTab, bindable in locked mode (ADR-0018,
        // verified on 0.44.3). Each grove is a tab; "home" (the dashboard) is tab
        // 1. Alt-<n> jumps to a tab by position, Alt-]/Alt-[ cycle. Alt-digit is
        // chosen because the harnesses (claude/codex) don't use it, so locked-mode
        // pass-through loses nothing; Ctrl-[ is avoided (it is ESC at the tty).
        bind "Alt 1" { GoToTab 1; }
        bind "Alt 2" { GoToTab 2; }
        bind "Alt 3" { GoToTab 3; }
        bind "Alt 4" { GoToTab 4; }
        bind "Alt 5" { GoToTab 5; }
        bind "Alt 6" { GoToTab 6; }
        bind "Alt 7" { GoToTab 7; }
        bind "Alt 8" { GoToTab 8; }
        bind "Alt 9" { GoToTab 9; }
        bind "Alt ]" { GoToNextTab; }
        bind "Alt [" { GoToPreviousTab; }
    }
}
"##;

/// Grove's bars-free layout *template*. `{{GROVE_BIN}}`, `{{SOCKET}}` and
/// `{{NAV_WASM}}` are substituted per launch (see [`render_layout`]). The "home"
/// tab holds two panes side by side (`split_direction="vertical"`): the [[nav
/// plugin]] as a fixed-width left sidebar — always visible from startup (ADR-0018)
/// — and the dashboard proxy as the focused main pane. The nav is named by the
/// same `file:` URL the leader keybind uses, so `Ctrl-o` focuses *this* running
/// instance. grove tabs the controller opens via `zellij action new-tab` sit
/// alongside the home tab. No tab-bar / status-bar plugin panes, so the composite
/// shows no zellij chrome.
const LAYOUT_TEMPLATE: &str = r##"// grove dashboard layout — generated by `grove tui` (ADR-0015/0016/0018, leaf
// 030/060/070). The "home" tab is a vertical split: the grove-nav plugin as a
// fixed 30-col left sidebar (always visible) + the dumb dashboard proxy as the
// focused main pane, which the controller renders into over the socket. grove
// tabs sit alongside, switched by the locked-mode GoToTab keybinds. Overwritten
// on every launch.
layout {
    tab name="home" split_direction="vertical" {
        // Always-on nav sidebar (the leader focuses this same file: instance).
        pane size=30 {
            plugin location="file:{{NAV_WASM}}"
        }
        // The dashboard proxy: the main, initially-focused pane.
        pane focus=true {
            name "grove"
            command "{{GROVE_BIN}}"
            args "__dash-proxy" "--socket" "{{SOCKET}}"
            start_suspended false
        }
    }
}
"##;

/// How long to wait for the dashboard proxy to connect before giving up. zellij
/// launching + the proxy pane spawning + connecting is sub-second in practice;
/// this is only a backstop against a proxy that never arrives.
const CONNECT_TIMEOUT: Duration = Duration::from_secs(15);

/// Launch the zellij substrate for `args.repo` (default: cwd's git root) and
/// serve the dashboard over the proxy seam until zellij (or the dashboard)
/// exits.
pub fn launch(args: &RepoArgs) -> Result<()> {
    let repo = repo::resolve(args.repo.as_deref())?;
    let grove_bin = std::env::current_exe().context("locating the running grove binary")?;

    // 1. Write the embedded config + materialised layout to the cache dir.
    let cache = cache_dir().context("resolving grove cache dir")?;
    std::fs::create_dir_all(&cache)
        .with_context(|| format!("creating cache dir {}", cache.display()))?;
    let config_path = cache.join("config.kdl");
    let layout_path = cache.join("layout.kdl");
    let nav_wasm_path = cache.join("grove-nav.wasm");

    // 2. Bind the controller socket BEFORE spawning zellij, so the proxy pane's
    //    connect() never races a missing socket.
    let socket = socket_path();
    let _ = std::fs::remove_file(&socket);
    let listener = UnixListener::bind(&socket)
        .with_context(|| format!("binding controller socket {}", socket.display()))?;

    // The nav plugin is written first so the config's leader bind and the layout's
    // sidebar pane both resolve to a real `file:` artifact (ADR-0018).
    std::fs::write(&nav_wasm_path, NAV_WASM)
        .with_context(|| format!("writing {}", nav_wasm_path.display()))?;
    std::fs::write(&config_path, render_config(&nav_wasm_path))
        .with_context(|| format!("writing {}", config_path.display()))?;
    std::fs::write(&layout_path, render_layout(&grove_bin, &socket, &nav_wasm_path))
        .with_context(|| format!("writing {}", layout_path.display()))?;

    // 3. Clear any stale session of the same name so config/layout changes take
    //    effect (best-effort: a no-op when none exists).
    let session = session_name(&repo);
    let _ = run_zellij_quiet(&["delete-session", &session, "--force"]);

    // 4. Spawn zellij as a child. It inherits the real tty and drives it; the
    //    controller never touches the tty (socket I/O only). Clear inherited
    //    ZELLIJ* so launching from inside a zellij session starts a fresh client.
    let mut child = Command::new("zellij")
        .arg("--config")
        .arg(&config_path)
        .arg("--new-session-with-layout")
        .arg(&layout_path)
        .arg("--session")
        .arg(&session)
        .env_remove("ZELLIJ")
        .env_remove("ZELLIJ_SESSION_NAME")
        .spawn()
        .map_err(friendly_spawn_err)?;

    // 5. Accept the dashboard proxy, watching the child so a zellij that dies on
    //    a bad config/layout surfaces as an error instead of an infinite block.
    let serve_result = match accept_proxy(&listener, &mut child) {
        Ok(stream) => crate::tui::serve(stream, repo),
        Err(e) => Err(e),
    };

    // 6. Teardown regardless of outcome: end the session (no-op if zellij already
    //    quit), reap the child, remove the socket.
    teardown(&mut child, &session, &socket);
    serve_result
}

/// Accept the dashboard proxy connection while watching the zellij `child`: if
/// zellij exits before connecting (bad config/layout, missing runtime), report
/// that rather than blocking forever; if nothing connects within
/// [`CONNECT_TIMEOUT`], give up with a clear error.
fn accept_proxy(listener: &UnixListener, child: &mut Child) -> Result<UnixStream> {
    listener
        .set_nonblocking(true)
        .context("setting controller listener non-blocking")?;
    let deadline = Instant::now() + CONNECT_TIMEOUT;
    loop {
        match listener.accept() {
            Ok((stream, _addr)) => {
                // The controller drives this socket in blocking mode with
                // per-read timeouts; clear any inherited non-blocking flag.
                stream
                    .set_nonblocking(false)
                    .context("clearing proxy stream non-blocking flag")?;
                return Ok(stream);
            }
            Err(ref e) if e.kind() == io::ErrorKind::WouldBlock => {
                if let Some(status) = child.try_wait().context("polling zellij child")? {
                    anyhow::bail!(
                        "zellij exited (status {:?}) before the dashboard connected — \
                         check the bundled config/layout or the installed zellij version",
                        status.code()
                    );
                }
                if Instant::now() >= deadline {
                    let _ = child.kill();
                    anyhow::bail!(
                        "timed out after {}s waiting for the dashboard proxy to connect",
                        CONNECT_TIMEOUT.as_secs()
                    );
                }
                std::thread::sleep(Duration::from_millis(20));
            }
            Err(e) => return Err(e).context("accepting dashboard proxy connection"),
        }
    }
}

/// Tear the substrate down: end the zellij session (a no-op on the happy path
/// where the user already quit zellij; needed when the dashboard quit via `q`
/// while zellij was still up), then reap the child and remove the socket. All
/// best-effort — teardown must not mask the serve outcome.
fn teardown(child: &mut Child, session: &str, socket: &Path) {
    let _ = run_zellij_quiet(&["delete-session", session, "--force"]);
    let _ = child.kill();
    let _ = child.wait();
    let _ = std::fs::remove_file(socket);
}

/// Run `zellij <args>` with stdio suppressed, for the control commands that must
/// not bleed onto the user's terminal (delete-session). Best-effort.
fn run_zellij_quiet(args: &[&str]) -> io::Result<std::process::ExitStatus> {
    Command::new("zellij")
        .args(args)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
}

/// Map a zellij spawn failure to a friendly error. The "depend on an installed
/// zellij" cut (node brief) handles a missing runtime with a clear message
/// rather than vendoring; a bundling decision is deferred to its own leaf/ADR.
fn friendly_spawn_err(e: io::Error) -> anyhow::Error {
    if e.kind() == io::ErrorKind::NotFound {
        anyhow::anyhow!(
            "zellij not found on PATH — grove's dashboard runs on an installed \
             zellij (see https://zellij.dev). Install it and retry."
        )
    } else {
        anyhow::Error::new(e).context("spawning zellij")
    }
}

/// Materialise the layout template: substitute the grove binary path, the
/// per-launch socket path, and the bundled nav-plugin's cache path (the home
/// sidebar pane).
fn render_layout(grove_bin: &Path, socket: &Path, nav_wasm: &Path) -> String {
    LAYOUT_TEMPLATE
        .replace("{{GROVE_BIN}}", &grove_bin.display().to_string())
        .replace("{{SOCKET}}", &socket.display().to_string())
        .replace("{{NAV_WASM}}", &nav_wasm.display().to_string())
}

/// Materialise the config template: substitute the bundled nav-plugin's cache
/// path into the leader's `LaunchOrFocusPlugin "file:…"` so it focuses the written
/// `.wasm` — the same instance the layout's sidebar launches (ADR-0018).
fn render_config(nav_wasm: &Path) -> String {
    CONFIG_TEMPLATE.replace("{{NAV_WASM}}", &nav_wasm.display().to_string())
}

/// The grove zellij cache dir: `$XDG_CACHE_HOME/grove/zellij/`, falling back to
/// `~/.cache/grove/zellij/`.
fn cache_dir() -> Result<PathBuf> {
    cache_dir_from(
        std::env::var_os("XDG_CACHE_HOME").as_deref(),
        std::env::var_os("HOME").as_deref(),
    )
}

/// Pure resolver for [`cache_dir`], parameterised on the two env inputs so it is
/// unit-testable. An empty `XDG_CACHE_HOME` is treated as unset (per the XDG
/// spec: relative/empty values are ignored).
fn cache_dir_from(xdg_cache_home: Option<&OsStr>, home: Option<&OsStr>) -> Result<PathBuf> {
    if let Some(xdg) = xdg_cache_home {
        if !xdg.is_empty() {
            return Ok(PathBuf::from(xdg).join("grove").join("zellij"));
        }
    }
    let home = home.context("neither XDG_CACHE_HOME nor HOME is set; cannot resolve cache dir")?;
    if home.is_empty() {
        anyhow::bail!("HOME is empty; cannot resolve cache dir");
    }
    Ok(PathBuf::from(home)
        .join(".cache")
        .join("grove")
        .join("zellij"))
}

/// A per-launch unix-socket path. Kept short (under macOS's ~104-byte `sun_path`
/// limit): `$XDG_RUNTIME_DIR` when set (Linux), else the system temp dir, plus a
/// pid-stamped name so concurrent launches don't collide.
fn socket_path() -> PathBuf {
    let dir = std::env::var_os("XDG_RUNTIME_DIR")
        .filter(|s| !s.is_empty())
        .map(PathBuf::from)
        .unwrap_or_else(std::env::temp_dir);
    dir.join(format!("grove-dash.{}.sock", std::process::id()))
}

/// The zellij session name for `repo`: `grove-<sanitised-basename>`, so two
/// repos' dashboards don't collide on one session. Non-`[A-Za-z0-9_-]` chars
/// become `-`; a basename that sanitises to nothing falls back to plain `grove`.
///
/// `pub(crate)` so the controller (`tui::serve`) derives the *same* session
/// name this head binary launched zellij with — the harness-driving layer
/// targets it via `zellij --session <name> action …` (leaf 040). Both call this
/// one pure function, so they match by construction.
pub(crate) fn session_name(repo: &Path) -> String {
    let base = repo
        .file_name()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_default();
    let cleaned: String = base
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '_' { c } else { '-' })
        .collect();
    let cleaned = cleaned.trim_matches('-');
    if cleaned.is_empty() {
        "grove".to_string()
    } else {
        format!("grove-{}", cleaned)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn layout_substitutes_binary_socket_and_nav() {
        let out = render_layout(
            Path::new("/opt/grove/bin/grove"),
            Path::new("/tmp/g.sock"),
            Path::new("/c/grove-nav.wasm"),
        );
        assert!(out.contains(r#"command "/opt/grove/bin/grove""#));
        assert!(out.contains(r#"args "__dash-proxy" "--socket" "/tmp/g.sock""#));
        // No placeholders survive substitution.
        assert!(!out.contains("{{"));
    }

    #[test]
    fn layout_home_tab_pairs_nav_sidebar_with_focused_dashboard() {
        // ADR-0018: the home tab is a vertical split — the grove-nav sidebar
        // (always visible from startup) beside the focused dashboard proxy. The
        // nav uses the same file: URL the leader keybind focuses.
        let out = render_layout(
            Path::new("/opt/grove"),
            Path::new("/tmp/g.sock"),
            Path::new("/c/grove-nav.wasm"),
        );
        assert!(
            out.contains(r#"tab name="home" split_direction="vertical""#),
            "home tab is not a vertical split:\n{out}"
        );
        assert!(
            out.contains(r#"plugin location="file:/c/grove-nav.wasm""#),
            "layout missing the nav sidebar plugin:\n{out}"
        );
        // The dashboard pane carries the initial focus, not the nav.
        assert!(
            out.contains("pane focus=true"),
            "dashboard pane is not focused:\n{out}"
        );
    }

    #[test]
    fn config_binds_tab_switching_in_locked_mode() {
        // ADR-0018: switching workspaces is native GoToTab keybinds that work in
        // default_mode "locked" (verified on 0.44.3) — the spine that fixes the
        // superseded focus-pane-id dead-end. The binds must sit inside the
        // `locked {` block, not an unlocked mode.
        let cfg = render_config(Path::new("/tmp/grove-nav.wasm"));
        let locked = locked_block(&cfg);
        for action in ["GoToTab 1", "GoToTab 9", "GoToNextTab", "GoToPreviousTab"] {
            assert!(
                locked.contains(action),
                "locked mode missing tab-switch action {action:?}:\n{locked}"
            );
        }
    }

    #[test]
    fn config_binds_leader_to_the_nav_by_file_url() {
        // ADR-0018: the leader (Ctrl-o) focuses the grove-nav plugin (the command
        // surface), naming it by the same file: URL the layout's sidebar uses so
        // it focuses that one running instance.
        let cfg = render_config(Path::new("/tmp/grove/grove-nav.wasm"));

        // The path is substituted into the leader bind; no placeholder survives.
        assert!(!cfg.contains("{{"), "an unsubstituted placeholder remains:\n{cfg}");
        let locked = locked_block(&cfg);
        assert!(
            locked.contains(r#"LaunchOrFocusPlugin "file:/tmp/grove/grove-nav.wasm""#),
            "leader does not focus the nav plugin by file URL in locked mode:\n{locked}"
        );
        // The dead-end unlock-to-Normal hop is gone...
        assert!(
            !cfg.contains(r#"SwitchToMode "Normal""#),
            "the dead-end Ctrl-o→Normal unlock should be gone:\n{cfg}"
        );
        // ...and so is the hint-less Alt-s scroll trap (and all unlocked modes):
        // the config is locked-only now.
        assert!(
            !cfg.contains("SwitchToMode \"Scroll\"") && !cfg.contains(r#"scroll {"#),
            "the trap-prone scroll mode should be removed:\n{cfg}"
        );
    }

    /// Extract the body of the `locked {` block from a config, so a test can
    /// assert a bind lands in locked mode (where it works while another app is
    /// focused) rather than an unlocked mode.
    fn locked_block(config: &str) -> String {
        let start = config.find("locked {").expect("config has a locked block");
        let after = &config[start..];
        let mut depth = 0i32;
        let mut end = after.len();
        for (i, ch) in after.char_indices() {
            match ch {
                '{' => depth += 1,
                '}' => {
                    depth -= 1;
                    if depth == 0 {
                        end = i + 1;
                        break;
                    }
                }
                _ => {}
            }
        }
        after[..end].to_string()
    }

    #[test]
    fn config_tames_chrome_and_keeps_ctrl_o_as_the_leader() {
        let cfg = render_config(Path::new("/tmp/grove-nav.wasm"));
        // The validated 020 knobs are present...
        for knob in [
            r#"default_mode "locked""#,
            "pane_frames false",
            "simplified_ui true",
            "show_release_notes false",
            "show_startup_tips false",
        ] {
            assert!(cfg.contains(knob), "config missing knob: {knob}");
        }
        // ...the keymap is defined from scratch (clear-defaults), the leader seam
        // is Ctrl-o (now → the nav plugin, ADR-0018), and Ctrl-g is gone entirely
        // (no `unbind` reliance — see the CONFIG_TEMPLATE doc comment and zellij
        // #2707).
        assert!(cfg.contains("keybinds clear-defaults=true"));
        assert!(cfg.contains(r#"bind "Ctrl o" { LaunchOrFocusPlugin "file:"#));
        // No Ctrl-g chord anywhere (we don't bind it and don't need to unbind it).
        assert!(!cfg.contains(r#""Ctrl g""#));
        // No `unbind` *directive* (clear-defaults makes it unnecessary; the word
        // may still appear in an explanatory comment, so match the directive form).
        assert!(!cfg.contains("\n    unbind") && !cfg.contains("        unbind"));
    }

    /// Validate the bundled config against the *real* installed zellij — this is
    /// what catches a malformed keybinds block (a bogus action name or mode),
    /// which `cargo` cannot. Skips gracefully when zellij isn't installed (CI
    /// without it). Note: `setup --check` validates *parse-correctness*, not the
    /// runtime keymap merge, so it guards regressions in the config's validity,
    /// not the live unlock behaviour (which needs a human at a tty).
    #[test]
    fn config_passes_zellij_setup_check() {
        if Command::new("zellij").arg("--version").output().is_err() {
            eprintln!("skipping config_passes_zellij_setup_check: zellij not installed");
            return;
        }
        let dir = tempfile::tempdir().expect("tempdir");
        // Write the real bundled plugin so the config's `file:` alias points at an
        // existing artifact, then render + validate exactly what launch() writes.
        let wasm = dir.path().join("grove-nav.wasm");
        std::fs::write(&wasm, NAV_WASM).expect("write nav wasm");
        let cfg = dir.path().join("config.kdl");
        std::fs::write(&cfg, render_config(&wasm)).expect("write config");
        let out = Command::new("zellij")
            .arg("--config")
            .arg(&cfg)
            .args(["setup", "--check"])
            .output()
            .expect("running zellij setup --check");
        let combined = format!(
            "{}{}",
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr)
        );
        assert!(
            combined.contains("Well defined"),
            "zellij rejected the bundled config:\n{combined}"
        );
    }

    #[test]
    fn cache_dir_prefers_xdg_then_home() {
        let xdg = cache_dir_from(Some(OsStr::new("/x/cache")), Some(OsStr::new("/home/u"))).unwrap();
        assert_eq!(xdg, PathBuf::from("/x/cache/grove/zellij"));

        // Empty XDG_CACHE_HOME is treated as unset → HOME fallback.
        let home = cache_dir_from(Some(OsStr::new("")), Some(OsStr::new("/home/u"))).unwrap();
        assert_eq!(home, PathBuf::from("/home/u/.cache/grove/zellij"));

        let none = cache_dir_from(None, Some(OsStr::new("/home/u"))).unwrap();
        assert_eq!(none, PathBuf::from("/home/u/.cache/grove/zellij"));
    }

    #[test]
    fn cache_dir_errors_without_any_env() {
        assert!(cache_dir_from(None, None).is_err());
        assert!(cache_dir_from(Some(OsStr::new("")), Some(OsStr::new(""))).is_err());
    }

    #[test]
    fn session_name_sanitises_and_namespaces() {
        assert_eq!(session_name(Path::new("/work/grove")), "grove-grove");
        assert_eq!(session_name(Path::new("/work/my repo.git")), "grove-my-repo-git");
        // A basename that sanitises to nothing falls back to plain `grove`.
        assert_eq!(session_name(Path::new("/work/...")), "grove");
    }
}
